name: Build mailcow Docker Images

on:
  push:
    branches: [ "master", "staging" ]
  workflow_dispatch:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  docker_image_builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      #- name: Login to Docker Hub
      #  uses: docker/login-action@v2
      #  with:
      #    username: ${{ secrets.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_TOKEN }}   
      
      - name: Prepair Image Builds
        run: |
          cp -v helper-scripts/docker-compose.override.yml.d/BUILD_FLAGS/docker-compose.override.yml docker-compose.preride.yml
          docker compose -f docker-compose.yml -f docker-compose.preride.yml config > docker-compose.override.yml
          rm -v docker-compose.yml && mv -v docker-compose.override.yml docker-compose.yml
        
      - name: Build and push
        uses: docker/bake-action@v3.1.0
        with:
          push: false
          set: |
            *.platform=linux/amd64,linux/arm64
